version: '3.8'

services:
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db


  #node api service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Asad
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}  